theme: jekyll-theme-midnight
title: Karaoke Forever
description: Open karaoke party system
collections:
  docs:
    output: true
    permalink: /:collection/:name/
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: default
